CREATE TABLE IF NOT EXISTS ai_user_state (
  user_id VARCHAR(64) NOT NULL PRIMARY KEY,
  purged TINYINT NOT NULL DEFAULT 0 COMMENT '1=永久清理，禁止旧请求重新创建数据',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI用户数据生命周期';
