package chat.liuxin.ai.security;

public enum AiCapability {
    CHAT,
    READ_PUBLIC_ARTICLES,
    SUMMARIZE_PUBLIC_ARTICLE,
    SEARCH_PUBLIC_ARTICLES,
    RECOMMEND_PUBLIC_ARTICLES,
    WRITE_DRAFT,
    CREATE_DRAFT_WITH_CONFIRMATION,
    PUBLISH_POST_WITH_CONFIRMATION,
    OFFLINE_POST_WITH_CONFIRMATION
}
